FROM node:18-alpine

ENV NODE_ENV development
ENV PNPM_HOME "/pnpm"
ENV PATH "$PNPM_HOME:$PATH"
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV PUPPETEER_EXECUTABLE_PATH /usr/bin/chromium-browser

RUN apk add --no-cache \
  curl \
  ffmpeg \
  fontconfig \
  chromium \
  nss \
  freetype \
  harfbuzz \
  ca-certificates \
  ttf-freefont \
  python3 \
  py3-pip \
  && pip3 install --upgrade pip \
  && pip3 install spotdl \
  && curl -O https://noto-website.storage.googleapis.com/pkgs/NotoSansCJKjp-hinted.zip \
  && mkdir -p /usr/share/fonts/NotoSansCJKjp \
  && unzip NotoSansCJKjp-hinted.zip -d /usr/share/fonts/NotoSansCJKjp/ \
  && rm NotoSansCJKjp-hinted.zip \
  && fc-cache -fv

WORKDIR /app

COPY . ./

RUN corepack enable
RUN pnpm install

EXPOSE 3000

CMD ["pnpm", "run", "dev"]