apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
        - name: app
          image: ghcr.io/iamtakagi/lapis:latest
          ports:
            - containerPort: 3000
        - name: postgres
          image: postgres:9.6
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
          volumeMounts:
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
        - name: nginx
          image: nginx:1.25.2-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
            - name: nginx-conf-default
              mountPath: /etc/nginx/conf.d/default.conf
            - name: nginx-log
              mountPath: /var/log/nginx
      volumes:
        - name: postgres-init
          hostPath:
            path: /postgres/init
            type: Directory
        - name: postgres-data
          hostPath:
            path: /postgres/data
            type: DirectoryOrCreate
        - name: nginx-conf
          hostPath:
            path: /nginx/nginx.conf
            type: Directory
        - name: nginx-conf-default
          hostPath:
            path: /nginx/conf.d/default.conf
            type: Directory
        - name: nginx-log
          hostPath:
            path: /nginx/log
            type: Directory
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-io-credentials
