apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: default
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000 

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: default
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: default
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

